---
- name: Set Up mac
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  become: no
  vars:
    dotfiles_repo: "git@github.com:708u/dotfiles.git"
    dotfiles_repo_version: main
    dotfiles_repo_local_destination: "~/ghq/github.com/708u/dotfiles"
    dotfiles_home: "~"
    dotfiles_files:
      - .gitconfig
      - .gitignore_global
      - .zshrc

  roles:
    - geerlingguy.dotfiles
    - dotfiles
    - font
    - homebrew
    - homebrew_cask
    - mac_app_store
    - mac_os
