- block:
    - name: determine if fira-code font exists
      stat:
        path: ~/Library/Fonts/ttf/FiraCode-Regular.ttf
      register: firaCode

    - block:
      - name: download fira code
        get_url:
          url: https://github.com/tonsky/FiraCode/releases/download/5.2/Fira_Code_v5.2.zip
          dest: ~/Downloads/Fira_Code_v5.2.zip

      - name: unzip fira code
        raw: unzip -u ~/Downloads/Fira_Code_v5.2.zip -d ~/Library/Fonts/
      when: not firaCode.stat.exists

      tags:
        - fira_code

    # NOTE: Gen shin gothic is uploaded by osdn uploader
    # so download this font manually via browser.
    - name: determine if gen shin gothic font exists
      stat:
        path: ~/Downloads/genshingothic-20150607.zip
      register: genShinGothic

    - name: unzip gen shin gothic
      raw: unzip -u ~/Downloads/genshingothic-20150607.zip -d ~/Library/Fonts/
      when: genShinGothic.stat.exists

  tags:
    - font
