- block:
    - name: update homebrew
      community.general.homebrew:
        update_homebrew: true

    - name: install homebrew packages
      community.general.homebrew:
        upgrade_all: yes
        name:
          - ansible
          - anyenv
          - bat
          - exa
          - fd
          - fzf
          - gh
          - ghq
          - git
          - grpcurl
          - jq
          - lsd
          - mas
          - node
          - procs
          - ripgrep
          - tig
          - tree
          - wget
          - yarn
          - zsh
  tags:
    - homebrew
