- block:
    - name: update homebrew
      community.general.homebrew:
        update_homebrew: true

    - name: install homebrew packages
      community.general.homebrew:
        upgrade_all: yes
        name:
          - ansible
          - anyenv
          - bat
          - clang-format
          - direnv
          - exa
          - fd
          - fzf
          - gh
          - ghq
          - git
          - libpng
          - graphviz # depends on libpng
          - grpcurl
          - jq
          - just
          - lsd
          - mas
          - node
          - procs
          - ripgrep
          - serverless
          - tig
          - tfenv
          - tree
          - wget
          - yarn
          - zsh
          - zsh-completions
  tags:
    - homebrew
