- name: install homebrew cask packages
  community.general.homebrew_cask:
    name:
      - alfred
      - appcleaner
      - cyberduck
      - discord
      - docker
      - google-chrome
      - google-japanese-ime
      - hyperswitch
      - iterm2
      - karabiner-elements
      - ngrok
      - notion
      - postman
      - tableplus
      - visual-studio-code
