- name: install homebrew cask packages
  community.general.homebrew_cask:
    name:
      - alfred
      - asana
      - appcleaner
      - bettertouchtool
      - cyberduck
      - discord
      - docker
      - dropbox
      - elgato-stream-deck
      - google-chrome
      - google-japanese-ime
      - graphviz
      - hyperswitch
      - iterm2
      - karabiner-elements
      - kindle
      - ngrok
      - notion
      - postman
      - tableplus
      - vagrant
      - visual-studio-code
      - virtualbox
      - zoom
